//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Account
    {
        
        [DataMember(Name="notifications")]
        private int notifications;
        
        public int Notifications
        {
            get
            {
                return notifications;
            }
            set
            {
                notifications = value;
            }
        }
    }
}
