//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Camera
    {
        
        [DataMember(Name="camera_id")]
        private int camera_id;
        
        [DataMember(Name="created_at")]
        private System.DateTime created_at;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="wifi_strength")]
        private int wifi_strength;
        
        [DataMember(Name="lfr_strength")]
        private int lfr_strength;
        
        [DataMember(Name="battery_voltage")]
        private int battery_voltage;
        
        [DataMember(Name="temperature")]
        private int temperature;
        
        [DataMember(Name="fw_version")]
        private string fw_version;
        
        [DataMember(Name="mac")]
        private string mac;
        
        [DataMember(Name="ipv")]
        private string ipv;
        
        [DataMember(Name="ip_address")]
        private string ip_address;
        
        [DataMember(Name="error_codes")]
        private int error_codes;
        
        [DataMember(Name="battery_alert_status")]
        private bool battery_alert_status;
        
        [DataMember(Name="temp_alert_status")]
        private bool temp_alert_status;
        
        [DataMember(Name="ac_power")]
        private bool ac_power;
        
        [DataMember(Name="light_sensor_ch0")]
        private int light_sensor_ch0;
        
        [DataMember(Name="light_sensor_ch1")]
        private int light_sensor_ch1;
        
        [DataMember(Name="light_sensor_data_valid")]
        private bool light_sensor_data_valid;
        
        [DataMember(Name="light_sensor_data_new")]
        private bool light_sensor_data_new;
        
        [DataMember(Name="time_first_video")]
        private int time_first_video;
        
        [DataMember(Name="time_108_boot")]
        private int time_108_boot;
        
        [DataMember(Name="time_wlan_connect")]
        private int time_wlan_connect;
        
        [DataMember(Name="time_dhcp_lease")]
        private int time_dhcp_lease;
        
        [DataMember(Name="time_dns_resolve")]
        private int time_dns_resolve;
        
        [DataMember(Name="lfr_108_wakeups")]
        private int lfr_108_wakeups;
        
        [DataMember(Name="total_108_wakeups")]
        private int total_108_wakeups;
        
        [DataMember(Name="lfr_tb_wakeups")]
        private int lfr_tb_wakeups;
        
        [DataMember(Name="total_tb_wakeups")]
        private int total_tb_wakeups;
        
        [DataMember(Name="wifi_connect_failure_count")]
        private int wifi_connect_failure_count;
        
        [DataMember(Name="dhcp_failure_count")]
        private int dhcp_failure_count;
        
        [DataMember(Name="socket_failure_count")]
        private int socket_failure_count;
        
        [DataMember(Name="dev_1")]
        private int dev_1;
        
        [DataMember(Name="dev_2")]
        private int dev_2;
        
        [DataMember(Name="dev_3")]
        private int dev_3;
        
        [DataMember(Name="unit_number")]
        private int unit_number;
        
        [DataMember(Name="serial")]
        private string serial;
        
        [DataMember(Name="lifetime_count")]
        private int lifetime_count;
        
        [DataMember(Name="lifetime_duration")]
        private int lifetime_duration;
        
        [DataMember(Name="pir_rejections")]
        private int pir_rejections;
        
        [DataMember(Name="sync_module_id")]
        private int sync_module_id;
        
        [DataMember(Name="network_id")]
        private int network_id;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="deleted_at")]
        private string deleted_at;
        
        [DataMember(Name="camera_key")]
        private string camera_key;
        
        [DataMember(Name="mac_address")]
        private string mac_address;
        
        [DataMember(Name="thumbnail")]
        private string thumbnail;
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="liveview_enabled")]
        private string liveview_enabled;
        
        [DataMember(Name="siren_enable")]
        private bool siren_enable;
        
        [DataMember(Name="siren_volume")]
        private string siren_volume;
        
        [DataMember(Name="onboarded")]
        private bool onboarded;
        
        [DataMember(Name="motion_sensitivity")]
        private int motion_sensitivity;
        
        [DataMember(Name="enabled")]
        private bool enabled;
        
        [DataMember(Name="alert_tone_enable")]
        private bool alert_tone_enable;
        
        [DataMember(Name="alert_tone_volume")]
        private int alert_tone_volume;
        
        [DataMember(Name="alert_repeat")]
        private string alert_repeat;
        
        [DataMember(Name="alert_interval")]
        private int alert_interval;
        
        [DataMember(Name="video_length")]
        private int video_length;
        
        [DataMember(Name="temp_alarm_enable")]
        private bool temp_alarm_enable;
        
        [DataMember(Name="temp_interval")]
        private int temp_interval;
        
        [DataMember(Name="temp_adjust")]
        private int temp_adjust;
        
        [DataMember(Name="temp_min")]
        private string temp_min;
        
        [DataMember(Name="temp_max")]
        private string temp_max;
        
        [DataMember(Name="temp_hysteresis")]
        private string temp_hysteresis;
        
        [DataMember(Name="illuminator_enable")]
        private string illuminator_enable;
        
        [DataMember(Name="illuminator_duration")]
        private int illuminator_duration;
        
        [DataMember(Name="illuminator_intensity")]
        private int illuminator_intensity;
        
        [DataMember(Name="battery_alarm_enable")]
        private bool battery_alarm_enable;
        
        [DataMember(Name="battery_voltage_interval")]
        private int battery_voltage_interval;
        
        [DataMember(Name="battery_voltage_threshold")]
        private int battery_voltage_threshold;
        
        [DataMember(Name="battery_voltage_hysteresis")]
        private int battery_voltage_hysteresis;
        
        [DataMember(Name="last_battery_alert")]
        private string last_battery_alert;
        
        [DataMember(Name="battery_alert_count")]
        private int battery_alert_count;
        
        [DataMember(Name="lfr_sync_interval")]
        private int lfr_sync_interval;
        
        [DataMember(Name="video_50_60hz")]
        private string video_50_60hz;
        
        [DataMember(Name="invert_image")]
        private bool invert_image;
        
        [DataMember(Name="flip_image")]
        private bool flip_image;
        
        [DataMember(Name="record_audio_enable")]
        private bool record_audio_enable;
        
        [DataMember(Name="clip_rate")]
        private int clip_rate;
        
        [DataMember(Name="liveview_rate")]
        private int liveview_rate;
        
        [DataMember(Name="max_resolution")]
        private string max_resolution;
        
        [DataMember(Name="auto_test")]
        private bool auto_test;
        
        [DataMember(Name="wifi_timeout")]
        private int wifi_timeout;
        
        [DataMember(Name="retry_count")]
        private int retry_count;
        
        [DataMember(Name="status")]
        private string status;
        
        [DataMember(Name="a1")]
        private bool a1;
        
        [DataMember(Name="last_temp_alert")]
        private string last_temp_alert;
        
        [DataMember(Name="temp_alert_count")]
        private int temp_alert_count;
        
        [DataMember(Name="last_wifi_alert")]
        private string last_wifi_alert;
        
        [DataMember(Name="wifi_alert_count")]
        private int wifi_alert_count;
        
        [DataMember(Name="last_lfr_alert")]
        private string last_lfr_alert;
        
        [DataMember(Name="lfr_alert_count")]
        private int lfr_alert_count;
        
        [DataMember(Name="last_offline_alert")]
        private System.Nullable<System.DateTime> last_offline_alert;
        
        [DataMember(Name="offline_alert_count")]
        private int offline_alert_count;
        
        [DataMember(Name="temp_alert_state")]
        private string temp_alert_state;
        
        [DataMember(Name="battery_state")]
        private string battery_state;
        
        [DataMember(Name="battery_check_time")]
        private System.DateTime battery_check_time;
        
        [DataMember(Name="motion_regions")]
        private int motion_regions;
        
        [DataMember(Name="mfg_main_type")]
        private string mfg_main_type;
        
        [DataMember(Name="mfg_main_range")]
        private int mfg_main_range;
        
        [DataMember(Name="mfg_mez_type")]
        private string mfg_mez_type;
        
        [DataMember(Name="mfg_mez_range")]
        private int mfg_mez_range;
        
        [DataMember(Name="type")]
        private string type;
        
        public int CameraId
        {
            get
            {
                return camera_id;
            }
            set
            {
                camera_id = value;
            }
        }
        
        public System.DateTime CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public int WifiStrength
        {
            get
            {
                return wifi_strength;
            }
            set
            {
                wifi_strength = value;
            }
        }
        
        public int LfrStrength
        {
            get
            {
                return lfr_strength;
            }
            set
            {
                lfr_strength = value;
            }
        }
        
        public int BatteryVoltage
        {
            get
            {
                return battery_voltage;
            }
            set
            {
                battery_voltage = value;
            }
        }
        
        public int Temperature
        {
            get
            {
                return temperature;
            }
            set
            {
                temperature = value;
            }
        }
        
        public string FwVersion
        {
            get
            {
                return fw_version;
            }
            set
            {
                fw_version = value;
            }
        }
        
        public string Mac
        {
            get
            {
                return mac;
            }
            set
            {
                mac = value;
            }
        }
        
        public string Ipv
        {
            get
            {
                return ipv;
            }
            set
            {
                ipv = value;
            }
        }
        
        public string IpAddress
        {
            get
            {
                return ip_address;
            }
            set
            {
                ip_address = value;
            }
        }
        
        public int ErrorCodes
        {
            get
            {
                return error_codes;
            }
            set
            {
                error_codes = value;
            }
        }
        
        public bool BatteryAlertStatus
        {
            get
            {
                return battery_alert_status;
            }
            set
            {
                battery_alert_status = value;
            }
        }
        
        public bool TempAlertStatus
        {
            get
            {
                return temp_alert_status;
            }
            set
            {
                temp_alert_status = value;
            }
        }
        
        public bool AcPower
        {
            get
            {
                return ac_power;
            }
            set
            {
                ac_power = value;
            }
        }
        
        public int LightSensorCh0
        {
            get
            {
                return light_sensor_ch0;
            }
            set
            {
                light_sensor_ch0 = value;
            }
        }
        
        public int LightSensorCh1
        {
            get
            {
                return light_sensor_ch1;
            }
            set
            {
                light_sensor_ch1 = value;
            }
        }
        
        public bool LightSensorDataValid
        {
            get
            {
                return light_sensor_data_valid;
            }
            set
            {
                light_sensor_data_valid = value;
            }
        }
        
        public bool LightSensorDataNew
        {
            get
            {
                return light_sensor_data_new;
            }
            set
            {
                light_sensor_data_new = value;
            }
        }
        
        public int TimeFirstVideo
        {
            get
            {
                return time_first_video;
            }
            set
            {
                time_first_video = value;
            }
        }
        
        public int Time108Boot
        {
            get
            {
                return time_108_boot;
            }
            set
            {
                time_108_boot = value;
            }
        }
        
        public int TimeWlanConnect
        {
            get
            {
                return time_wlan_connect;
            }
            set
            {
                time_wlan_connect = value;
            }
        }
        
        public int TimeDhcpLease
        {
            get
            {
                return time_dhcp_lease;
            }
            set
            {
                time_dhcp_lease = value;
            }
        }
        
        public int TimeDnsResolve
        {
            get
            {
                return time_dns_resolve;
            }
            set
            {
                time_dns_resolve = value;
            }
        }
        
        public int Lfr108Wakeups
        {
            get
            {
                return lfr_108_wakeups;
            }
            set
            {
                lfr_108_wakeups = value;
            }
        }
        
        public int Total108Wakeups
        {
            get
            {
                return total_108_wakeups;
            }
            set
            {
                total_108_wakeups = value;
            }
        }
        
        public int LfrTbWakeups
        {
            get
            {
                return lfr_tb_wakeups;
            }
            set
            {
                lfr_tb_wakeups = value;
            }
        }
        
        public int TotalTbWakeups
        {
            get
            {
                return total_tb_wakeups;
            }
            set
            {
                total_tb_wakeups = value;
            }
        }
        
        public int WifiConnectFailureCount
        {
            get
            {
                return wifi_connect_failure_count;
            }
            set
            {
                wifi_connect_failure_count = value;
            }
        }
        
        public int DhcpFailureCount
        {
            get
            {
                return dhcp_failure_count;
            }
            set
            {
                dhcp_failure_count = value;
            }
        }
        
        public int SocketFailureCount
        {
            get
            {
                return socket_failure_count;
            }
            set
            {
                socket_failure_count = value;
            }
        }
        
        public int Dev1
        {
            get
            {
                return dev_1;
            }
            set
            {
                dev_1 = value;
            }
        }
        
        public int Dev2
        {
            get
            {
                return dev_2;
            }
            set
            {
                dev_2 = value;
            }
        }
        
        public int Dev3
        {
            get
            {
                return dev_3;
            }
            set
            {
                dev_3 = value;
            }
        }
        
        public int UnitNumber
        {
            get
            {
                return unit_number;
            }
            set
            {
                unit_number = value;
            }
        }
        
        public string Serial
        {
            get
            {
                return serial;
            }
            set
            {
                serial = value;
            }
        }
        
        public int LifetimeCount
        {
            get
            {
                return lifetime_count;
            }
            set
            {
                lifetime_count = value;
            }
        }
        
        public int LifetimeDuration
        {
            get
            {
                return lifetime_duration;
            }
            set
            {
                lifetime_duration = value;
            }
        }
        
        public int PirRejections
        {
            get
            {
                return pir_rejections;
            }
            set
            {
                pir_rejections = value;
            }
        }
        
        public int SyncModuleId
        {
            get
            {
                return sync_module_id;
            }
            set
            {
                sync_module_id = value;
            }
        }
        
        public int NetworkId
        {
            get
            {
                return network_id;
            }
            set
            {
                network_id = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public string DeletedAt
        {
            get
            {
                return deleted_at;
            }
            set
            {
                deleted_at = value;
            }
        }
        
        public string CameraKey
        {
            get
            {
                return camera_key;
            }
            set
            {
                camera_key = value;
            }
        }
        
        public string MacAddress
        {
            get
            {
                return mac_address;
            }
            set
            {
                mac_address = value;
            }
        }
        
        public string Thumbnail
        {
            get
            {
                return thumbnail;
            }
            set
            {
                thumbnail = value;
            }
        }
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public string LiveviewEnabled
        {
            get
            {
                return liveview_enabled;
            }
            set
            {
                liveview_enabled = value;
            }
        }
        
        public bool SirenEnable
        {
            get
            {
                return siren_enable;
            }
            set
            {
                siren_enable = value;
            }
        }
        
        public string SirenVolume
        {
            get
            {
                return siren_volume;
            }
            set
            {
                siren_volume = value;
            }
        }
        
        public bool Onboarded
        {
            get
            {
                return onboarded;
            }
            set
            {
                onboarded = value;
            }
        }
        
        public int MotionSensitivity
        {
            get
            {
                return motion_sensitivity;
            }
            set
            {
                motion_sensitivity = value;
            }
        }
        
        public bool Enabled
        {
            get
            {
                return enabled;
            }
            set
            {
                enabled = value;
            }
        }
        
        public bool AlertToneEnable
        {
            get
            {
                return alert_tone_enable;
            }
            set
            {
                alert_tone_enable = value;
            }
        }
        
        public int AlertToneVolume
        {
            get
            {
                return alert_tone_volume;
            }
            set
            {
                alert_tone_volume = value;
            }
        }
        
        public string AlertRepeat
        {
            get
            {
                return alert_repeat;
            }
            set
            {
                alert_repeat = value;
            }
        }
        
        public int AlertInterval
        {
            get
            {
                return alert_interval;
            }
            set
            {
                alert_interval = value;
            }
        }
        
        public int VideoLength
        {
            get
            {
                return video_length;
            }
            set
            {
                video_length = value;
            }
        }
        
        public bool TempAlarmEnable
        {
            get
            {
                return temp_alarm_enable;
            }
            set
            {
                temp_alarm_enable = value;
            }
        }
        
        public int TempInterval
        {
            get
            {
                return temp_interval;
            }
            set
            {
                temp_interval = value;
            }
        }
        
        public int TempAdjust
        {
            get
            {
                return temp_adjust;
            }
            set
            {
                temp_adjust = value;
            }
        }
        
        public string TempMin
        {
            get
            {
                return temp_min;
            }
            set
            {
                temp_min = value;
            }
        }
        
        public string TempMax
        {
            get
            {
                return temp_max;
            }
            set
            {
                temp_max = value;
            }
        }
        
        public string TempHysteresis
        {
            get
            {
                return temp_hysteresis;
            }
            set
            {
                temp_hysteresis = value;
            }
        }
        
        public string IlluminatorEnable
        {
            get
            {
                return illuminator_enable;
            }
            set
            {
                illuminator_enable = value;
            }
        }
        
        public int IlluminatorDuration
        {
            get
            {
                return illuminator_duration;
            }
            set
            {
                illuminator_duration = value;
            }
        }
        
        public int IlluminatorIntensity
        {
            get
            {
                return illuminator_intensity;
            }
            set
            {
                illuminator_intensity = value;
            }
        }
        
        public bool BatteryAlarmEnable
        {
            get
            {
                return battery_alarm_enable;
            }
            set
            {
                battery_alarm_enable = value;
            }
        }
        
        public int BatteryVoltageInterval
        {
            get
            {
                return battery_voltage_interval;
            }
            set
            {
                battery_voltage_interval = value;
            }
        }
        
        public int BatteryVoltageThreshold
        {
            get
            {
                return battery_voltage_threshold;
            }
            set
            {
                battery_voltage_threshold = value;
            }
        }
        
        public int BatteryVoltageHysteresis
        {
            get
            {
                return battery_voltage_hysteresis;
            }
            set
            {
                battery_voltage_hysteresis = value;
            }
        }
        
        public string LastBatteryAlert
        {
            get
            {
                return last_battery_alert;
            }
            set
            {
                last_battery_alert = value;
            }
        }
        
        public int BatteryAlertCount
        {
            get
            {
                return battery_alert_count;
            }
            set
            {
                battery_alert_count = value;
            }
        }
        
        public int LfrSyncInterval
        {
            get
            {
                return lfr_sync_interval;
            }
            set
            {
                lfr_sync_interval = value;
            }
        }
        
        public string Video5060hz
        {
            get
            {
                return video_50_60hz;
            }
            set
            {
                video_50_60hz = value;
            }
        }
        
        public bool InvertImage
        {
            get
            {
                return invert_image;
            }
            set
            {
                invert_image = value;
            }
        }
        
        public bool FlipImage
        {
            get
            {
                return flip_image;
            }
            set
            {
                flip_image = value;
            }
        }
        
        public bool RecordAudioEnable
        {
            get
            {
                return record_audio_enable;
            }
            set
            {
                record_audio_enable = value;
            }
        }
        
        public int ClipRate
        {
            get
            {
                return clip_rate;
            }
            set
            {
                clip_rate = value;
            }
        }
        
        public int LiveviewRate
        {
            get
            {
                return liveview_rate;
            }
            set
            {
                liveview_rate = value;
            }
        }
        
        public string MaxResolution
        {
            get
            {
                return max_resolution;
            }
            set
            {
                max_resolution = value;
            }
        }
        
        public bool AutoTest
        {
            get
            {
                return auto_test;
            }
            set
            {
                auto_test = value;
            }
        }
        
        public int WifiTimeout
        {
            get
            {
                return wifi_timeout;
            }
            set
            {
                wifi_timeout = value;
            }
        }
        
        public int RetryCount
        {
            get
            {
                return retry_count;
            }
            set
            {
                retry_count = value;
            }
        }
        
        public string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
        
        public bool A1
        {
            get
            {
                return a1;
            }
            set
            {
                a1 = value;
            }
        }
        
        public string LastTempAlert
        {
            get
            {
                return last_temp_alert;
            }
            set
            {
                last_temp_alert = value;
            }
        }
        
        public int TempAlertCount
        {
            get
            {
                return temp_alert_count;
            }
            set
            {
                temp_alert_count = value;
            }
        }
        
        public string LastWifiAlert
        {
            get
            {
                return last_wifi_alert;
            }
            set
            {
                last_wifi_alert = value;
            }
        }
        
        public int WifiAlertCount
        {
            get
            {
                return wifi_alert_count;
            }
            set
            {
                wifi_alert_count = value;
            }
        }
        
        public string LastLfrAlert
        {
            get
            {
                return last_lfr_alert;
            }
            set
            {
                last_lfr_alert = value;
            }
        }
        
        public int LfrAlertCount
        {
            get
            {
                return lfr_alert_count;
            }
            set
            {
                lfr_alert_count = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastOfflineAlert
        {
            get
            {
                return last_offline_alert;
            }
            set
            {
                last_offline_alert = value;
            }
        }
        
        public int OfflineAlertCount
        {
            get
            {
                return offline_alert_count;
            }
            set
            {
                offline_alert_count = value;
            }
        }
        
        public string TempAlertState
        {
            get
            {
                return temp_alert_state;
            }
            set
            {
                temp_alert_state = value;
            }
        }
        
        public string BatteryState
        {
            get
            {
                return battery_state;
            }
            set
            {
                battery_state = value;
            }
        }
        
        public System.DateTime BatteryCheckTime
        {
            get
            {
                return battery_check_time;
            }
            set
            {
                battery_check_time = value;
            }
        }
        
        public int MotionRegions
        {
            get
            {
                return motion_regions;
            }
            set
            {
                motion_regions = value;
            }
        }
        
        public string MfgMainType
        {
            get
            {
                return mfg_main_type;
            }
            set
            {
                mfg_main_type = value;
            }
        }
        
        public int MfgMainRange
        {
            get
            {
                return mfg_main_range;
            }
            set
            {
                mfg_main_range = value;
            }
        }
        
        public string MfgMezType
        {
            get
            {
                return mfg_mez_type;
            }
            set
            {
                mfg_mez_type = value;
            }
        }
        
        public int MfgMezRange
        {
            get
            {
                return mfg_mez_range;
            }
            set
            {
                mfg_mez_range = value;
            }
        }
        
        public string Type
        {
            get
            {
                return type;
            }
            set
            {
                type = value;
            }
        }
    }
}
