//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Client
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="created_at")]
        private string created_at;
        
        [DataMember(Name="updated_at")]
        private string updated_at;
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="notify_sound")]
        private string notify_sound;
        
        [DataMember(Name="client_type")]
        private string client_type;
        
        [DataMember(Name="client_specifier")]
        private string client_specifier;
        
        [DataMember(Name="notification_key")]
        private string notification_key;
        
        [DataMember(Name="aws_key")]
        private string aws_key;
        
        [DataMember(Name="os_version")]
        private string os_version;
        
        [DataMember(Name="device_identifier")]
        private string device_identifier;
        
        [DataMember(Name="app_version")]
        private string app_version;
        
        [DataMember(Name="unique_id")]
        private string unique_id;
        
        [DataMember(Name="home")]
        private string home;
        
        [DataMember(Name="ssid")]
        private string ssid;
        
        [DataMember(Name="ssid_updated_at")]
        private string ssid_updated_at;
        
        [DataMember(Name="enabled_notifications")]
        private int enabled_notifications;
        
        [DataMember(Name="client_options")]
        private string client_options;
        
        [DataMember(Name="user_id")]
        private int user_id;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public string CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public string UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public string NotifySound
        {
            get
            {
                return notify_sound;
            }
            set
            {
                notify_sound = value;
            }
        }
        
        public string ClientType
        {
            get
            {
                return client_type;
            }
            set
            {
                client_type = value;
            }
        }
        
        public string ClientSpecifier
        {
            get
            {
                return client_specifier;
            }
            set
            {
                client_specifier = value;
            }
        }
        
        public string NotificationKey
        {
            get
            {
                return notification_key;
            }
            set
            {
                notification_key = value;
            }
        }
        
        public string AwsKey
        {
            get
            {
                return aws_key;
            }
            set
            {
                aws_key = value;
            }
        }
        
        public string OsVersion
        {
            get
            {
                return os_version;
            }
            set
            {
                os_version = value;
            }
        }
        
        public string DeviceIdentifier
        {
            get
            {
                return device_identifier;
            }
            set
            {
                device_identifier = value;
            }
        }
        
        public string AppVersion
        {
            get
            {
                return app_version;
            }
            set
            {
                app_version = value;
            }
        }
        
        public string UniqueId
        {
            get
            {
                return unique_id;
            }
            set
            {
                unique_id = value;
            }
        }
        
        public string Home
        {
            get
            {
                return home;
            }
            set
            {
                home = value;
            }
        }
        
        public string Ssid
        {
            get
            {
                return ssid;
            }
            set
            {
                ssid = value;
            }
        }
        
        public string SsidUpdatedAt
        {
            get
            {
                return ssid_updated_at;
            }
            set
            {
                ssid_updated_at = value;
            }
        }
        
        public int EnabledNotifications
        {
            get
            {
                return enabled_notifications;
            }
            set
            {
                enabled_notifications = value;
            }
        }
        
        public string ClientOptions
        {
            get
            {
                return client_options;
            }
            set
            {
                client_options = value;
            }
        }
        
        public int UserId
        {
            get
            {
                return user_id;
            }
            set
            {
                user_id = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
    }
}
