//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class CommandInformation
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="created_at")]
        private System.DateTime created_at;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="execute_time")]
        private System.DateTime execute_time;
        
        [DataMember(Name="command")]
        private string command;
        
        [DataMember(Name="state_stage")]
        private string state_stage;
        
        [DataMember(Name="stage_rest")]
        private System.DateTime stage_rest;
        
        [DataMember(Name="stage_cs_db")]
        private string stage_cs_db;
        
        [DataMember(Name="stage_cs_sent")]
        private string stage_cs_sent;
        
        [DataMember(Name="stage_sm")]
        private string stage_sm;
        
        [DataMember(Name="stage_dev")]
        private string stage_dev;
        
        [DataMember(Name="stage_is")]
        private string stage_is;
        
        [DataMember(Name="stage_lv")]
        private string stage_lv;
        
        [DataMember(Name="stage_vs")]
        private string stage_vs;
        
        [DataMember(Name="state_condition")]
        private string state_condition;
        
        [DataMember(Name="sm_ack")]
        private string sm_ack;
        
        [DataMember(Name="lfr_ack")]
        private string lfr_ack;
        
        [DataMember(Name="sequence")]
        private string sequence;
        
        [DataMember(Name="attempts")]
        private int attempts;
        
        [DataMember(Name="transaction")]
        private string transaction;
        
        [DataMember(Name="player_transaction")]
        private string player_transaction;
        
        [DataMember(Name="server")]
        private string server;
        
        [DataMember(Name="duration")]
        private string duration;
        
        [DataMember(Name="by_whom")]
        private string by_whom;
        
        [DataMember(Name="diagnostic")]
        private bool diagnostic;
        
        [DataMember(Name="debug")]
        private string debug;
        
        [DataMember(Name="target")]
        private string target;
        
        [DataMember(Name="target_id")]
        private string target_id;
        
        [DataMember(Name="parent_command_id")]
        private string parent_command_id;
        
        [DataMember(Name="camera_id")]
        private int camera_id;
        
        [DataMember(Name="siren_id")]
        private string siren_id;
        
        [DataMember(Name="firmware_id")]
        private string firmware_id;
        
        [DataMember(Name="network_id")]
        private int network_id;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        [DataMember(Name="sync_module_id")]
        private int sync_module_id;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public System.DateTime CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public System.DateTime ExecuteTime
        {
            get
            {
                return execute_time;
            }
            set
            {
                execute_time = value;
            }
        }
        
        public string Command
        {
            get
            {
                return command;
            }
            set
            {
                command = value;
            }
        }
        
        public string StateStage
        {
            get
            {
                return state_stage;
            }
            set
            {
                state_stage = value;
            }
        }
        
        public System.DateTime StageRest
        {
            get
            {
                return stage_rest;
            }
            set
            {
                stage_rest = value;
            }
        }
        
        public string StageCsDb
        {
            get
            {
                return stage_cs_db;
            }
            set
            {
                stage_cs_db = value;
            }
        }
        
        public string StageCsSent
        {
            get
            {
                return stage_cs_sent;
            }
            set
            {
                stage_cs_sent = value;
            }
        }
        
        public string StageSm
        {
            get
            {
                return stage_sm;
            }
            set
            {
                stage_sm = value;
            }
        }
        
        public string StageDev
        {
            get
            {
                return stage_dev;
            }
            set
            {
                stage_dev = value;
            }
        }
        
        public string StageIs
        {
            get
            {
                return stage_is;
            }
            set
            {
                stage_is = value;
            }
        }
        
        public string StageLv
        {
            get
            {
                return stage_lv;
            }
            set
            {
                stage_lv = value;
            }
        }
        
        public string StageVs
        {
            get
            {
                return stage_vs;
            }
            set
            {
                stage_vs = value;
            }
        }
        
        public string StateCondition
        {
            get
            {
                return state_condition;
            }
            set
            {
                state_condition = value;
            }
        }
        
        public string SmAck
        {
            get
            {
                return sm_ack;
            }
            set
            {
                sm_ack = value;
            }
        }
        
        public string LfrAck
        {
            get
            {
                return lfr_ack;
            }
            set
            {
                lfr_ack = value;
            }
        }
        
        public string Sequence
        {
            get
            {
                return sequence;
            }
            set
            {
                sequence = value;
            }
        }
        
        public int Attempts
        {
            get
            {
                return attempts;
            }
            set
            {
                attempts = value;
            }
        }
        
        public string Transaction
        {
            get
            {
                return transaction;
            }
            set
            {
                transaction = value;
            }
        }
        
        public string PlayerTransaction
        {
            get
            {
                return player_transaction;
            }
            set
            {
                player_transaction = value;
            }
        }
        
        public string Server
        {
            get
            {
                return server;
            }
            set
            {
                server = value;
            }
        }
        
        public string Duration
        {
            get
            {
                return duration;
            }
            set
            {
                duration = value;
            }
        }
        
        public string ByWhom
        {
            get
            {
                return by_whom;
            }
            set
            {
                by_whom = value;
            }
        }
        
        public bool Diagnostic
        {
            get
            {
                return diagnostic;
            }
            set
            {
                diagnostic = value;
            }
        }
        
        public string Debug
        {
            get
            {
                return debug;
            }
            set
            {
                debug = value;
            }
        }
        
        public string Target
        {
            get
            {
                return target;
            }
            set
            {
                target = value;
            }
        }
        
        public string TargetId
        {
            get
            {
                return target_id;
            }
            set
            {
                target_id = value;
            }
        }
        
        public string ParentCommandId
        {
            get
            {
                return parent_command_id;
            }
            set
            {
                parent_command_id = value;
            }
        }
        
        public int CameraId
        {
            get
            {
                return camera_id;
            }
            set
            {
                camera_id = value;
            }
        }
        
        public string SirenId
        {
            get
            {
                return siren_id;
            }
            set
            {
                siren_id = value;
            }
        }
        
        public string FirmwareId
        {
            get
            {
                return firmware_id;
            }
            set
            {
                firmware_id = value;
            }
        }
        
        public int NetworkId
        {
            get
            {
                return network_id;
            }
            set
            {
                network_id = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
        
        public int SyncModuleId
        {
            get
            {
                return sync_module_id;
            }
            set
            {
                sync_module_id = value;
            }
        }
    }
}
