//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Device
    {
        
        [DataMember(Name="device_type")]
        private string device_type;
        
        [DataMember(Name="device_id")]
        private int device_id;
        
        [DataMember(Name="type")]
        private string type;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="thumbnail")]
        private string thumbnail;
        
        [DataMember(Name="active")]
        private string active;
        
        [DataMember(Name="notifications")]
        private int notifications;
        
        [DataMember(Name="warning")]
        private int warning;
        
        [DataMember(Name="error_msg")]
        private string error_msg;
        
        [DataMember(Name="status")]
        private string status;
        
        [DataMember(Name="enabled")]
        private bool enabled;
        
        [DataMember(Name="armed")]
        private bool armed;
        
        [DataMember(Name="errors")]
        private int errors;
        
        [DataMember(Name="wifi_strength")]
        private int wifi_strength;
        
        [DataMember(Name="lfr_strength")]
        private int lfr_strength;
        
        [DataMember(Name="temp")]
        private int temp;
        
        [DataMember(Name="battery")]
        private int battery;
        
        [DataMember(Name="battery_state")]
        private string battery_state;
        
        [DataMember(Name="usage_rate")]
        private bool usage_rate;
        
        [DataMember(Name="last_hb")]
        private System.Nullable<System.DateTime> last_hb;
        
        public string DeviceType
        {
            get
            {
                return device_type;
            }
            set
            {
                device_type = value;
            }
        }
        
        public int DeviceId
        {
            get
            {
                return device_id;
            }
            set
            {
                device_id = value;
            }
        }
        
        public string Type
        {
            get
            {
                return type;
            }
            set
            {
                type = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public string Thumbnail
        {
            get
            {
                return thumbnail;
            }
            set
            {
                thumbnail = value;
            }
        }
        
        public string Active
        {
            get
            {
                return active;
            }
            set
            {
                active = value;
            }
        }
        
        public int Notifications
        {
            get
            {
                return notifications;
            }
            set
            {
                notifications = value;
            }
        }
        
        public int Warning
        {
            get
            {
                return warning;
            }
            set
            {
                warning = value;
            }
        }
        
        public string ErrorMsg
        {
            get
            {
                return error_msg;
            }
            set
            {
                error_msg = value;
            }
        }
        
        public string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
        
        public bool Enabled
        {
            get
            {
                return enabled;
            }
            set
            {
                enabled = value;
            }
        }
        
        public bool Armed
        {
            get
            {
                return armed;
            }
            set
            {
                armed = value;
            }
        }
        
        public int Errors
        {
            get
            {
                return errors;
            }
            set
            {
                errors = value;
            }
        }
        
        public int WifiStrength
        {
            get
            {
                return wifi_strength;
            }
            set
            {
                wifi_strength = value;
            }
        }
        
        public int LfrStrength
        {
            get
            {
                return lfr_strength;
            }
            set
            {
                lfr_strength = value;
            }
        }
        
        public int Temp
        {
            get
            {
                return temp;
            }
            set
            {
                temp = value;
            }
        }
        
        public int Battery
        {
            get
            {
                return battery;
            }
            set
            {
                battery = value;
            }
        }
        
        public string BatteryState
        {
            get
            {
                return battery_state;
            }
            set
            {
                battery_state = value;
            }
        }
        
        public bool UsageRate
        {
            get
            {
                return usage_rate;
            }
            set
            {
                usage_rate = value;
            }
        }
        
        public System.Nullable<System.DateTime> LastHb
        {
            get
            {
                return last_hb;
            }
            set
            {
                last_hb = value;
            }
        }
    }
}
