//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Event
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="created_at")]
        private System.DateTime created_at;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="type")]
        private string type;
        
        [DataMember(Name="notified")]
        private bool notified;
        
        [DataMember(Name="duration")]
        private object duration;
        
        [DataMember(Name="status")]
        private string status;
        
        [DataMember(Name="target")]
        private object target;
        
        [DataMember(Name="target_id")]
        private object target_id;
        
        [DataMember(Name="data")]
        private object data;
        
        [DataMember(Name="command_id")]
        private System.Nullable<int> command_id;
        
        [DataMember(Name="camera_id")]
        private System.Nullable<int> camera_id;
        
        [DataMember(Name="siren_id")]
        private object siren_id;
        
        [DataMember(Name="sync_module_id")]
        private System.Nullable<int> sync_module_id;
        
        [DataMember(Name="network_id")]
        private System.Nullable<int> network_id;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        [DataMember(Name="syncmodule")]
        private System.Nullable<int> syncmodule;
        
        [DataMember(Name="camera")]
        private System.Nullable<int> camera;
        
        [DataMember(Name="siren")]
        private object siren;
        
        [DataMember(Name="account")]
        private int account;
        
        [DataMember(Name="camera_name")]
        private string camera_name;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public System.DateTime CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public string Type
        {
            get
            {
                return type;
            }
            set
            {
                type = value;
            }
        }
        
        public bool Notified
        {
            get
            {
                return notified;
            }
            set
            {
                notified = value;
            }
        }
        
        public object Duration
        {
            get
            {
                return duration;
            }
            set
            {
                duration = value;
            }
        }
        
        public string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
        
        public object Target
        {
            get
            {
                return target;
            }
            set
            {
                target = value;
            }
        }
        
        public object TargetId
        {
            get
            {
                return target_id;
            }
            set
            {
                target_id = value;
            }
        }
        
        public object Data
        {
            get
            {
                return data;
            }
            set
            {
                data = value;
            }
        }
        
        public System.Nullable<int> CommandId
        {
            get
            {
                return command_id;
            }
            set
            {
                command_id = value;
            }
        }
        
        public System.Nullable<int> CameraId
        {
            get
            {
                return camera_id;
            }
            set
            {
                camera_id = value;
            }
        }
        
        public object SirenId
        {
            get
            {
                return siren_id;
            }
            set
            {
                siren_id = value;
            }
        }
        
        public System.Nullable<int> SyncModuleId
        {
            get
            {
                return sync_module_id;
            }
            set
            {
                sync_module_id = value;
            }
        }
        
        public System.Nullable<int> NetworkId
        {
            get
            {
                return network_id;
            }
            set
            {
                network_id = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
        
        public System.Nullable<int> Syncmodule
        {
            get
            {
                return syncmodule;
            }
            set
            {
                syncmodule = value;
            }
        }
        
        public System.Nullable<int> Camera
        {
            get
            {
                return camera;
            }
            set
            {
                camera = value;
            }
        }
        
        public object Siren
        {
            get
            {
                return siren;
            }
            set
            {
                siren = value;
            }
        }
        
        public int Account
        {
            get
            {
                return account;
            }
            set
            {
                account = value;
            }
        }
        
        public string CameraName
        {
            get
            {
                return camera_name;
            }
            set
            {
                camera_name = value;
            }
        }
    }
}
