//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class HomeScreen
    {
        
        [DataMember(Name="account")]
        private BlinkdotNet.Entities.Account account;
        
        [DataMember(Name="network")]
        private BlinkdotNet.Entities.Network network;
        
        [DataMember(Name="devices")]
        private System.Collections.Generic.List<BlinkdotNet.Entities.Device> devices;
        
        public BlinkdotNet.Entities.Account Account
        {
            get
            {
                return account;
            }
            set
            {
                account = value;
            }
        }
        
        public BlinkdotNet.Entities.Network Network
        {
            get
            {
                return network;
            }
            set
            {
                network = value;
            }
        }
        
        public System.Collections.Generic.List<BlinkdotNet.Entities.Device> Devices
        {
            get
            {
                return devices;
            }
            set
            {
                devices = value;
            }
        }
    }
}
