//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Module
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="created_at")]
        private System.DateTime created_at;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="last_activity")]
        private string last_activity;
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="fw_version")]
        private string fw_version;
        
        [DataMember(Name="mac_address")]
        private string mac_address;
        
        [DataMember(Name="ip_address")]
        private string ip_address;
        
        [DataMember(Name="lfr_frequency")]
        private string lfr_frequency;
        
        [DataMember(Name="serial")]
        private string serial;
        
        [DataMember(Name="status")]
        private string status;
        
        [DataMember(Name="onboarded")]
        private bool onboarded;
        
        [DataMember(Name="server")]
        private string server;
        
        [DataMember(Name="last_hb")]
        private System.DateTime last_hb;
        
        [DataMember(Name="os_version")]
        private string os_version;
        
        [DataMember(Name="last_wifi_alert")]
        private string last_wifi_alert;
        
        [DataMember(Name="wifi_alert_count")]
        private int wifi_alert_count;
        
        [DataMember(Name="last_offline_alert")]
        private System.DateTime last_offline_alert;
        
        [DataMember(Name="offline_alert_count")]
        private int offline_alert_count;
        
        [DataMember(Name="table_update_sequence")]
        private int table_update_sequence;
        
        [DataMember(Name="feature_plan_id")]
        private string feature_plan_id;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        [DataMember(Name="network_id")]
        private int network_id;
        
        [DataMember(Name="wifi_strength")]
        private int wifi_strength;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public System.DateTime CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public string LastActivity
        {
            get
            {
                return last_activity;
            }
            set
            {
                last_activity = value;
            }
        }
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public string FwVersion
        {
            get
            {
                return fw_version;
            }
            set
            {
                fw_version = value;
            }
        }
        
        public string MacAddress
        {
            get
            {
                return mac_address;
            }
            set
            {
                mac_address = value;
            }
        }
        
        public string IpAddress
        {
            get
            {
                return ip_address;
            }
            set
            {
                ip_address = value;
            }
        }
        
        public string LfrFrequency
        {
            get
            {
                return lfr_frequency;
            }
            set
            {
                lfr_frequency = value;
            }
        }
        
        public string Serial
        {
            get
            {
                return serial;
            }
            set
            {
                serial = value;
            }
        }
        
        public string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
        
        public bool Onboarded
        {
            get
            {
                return onboarded;
            }
            set
            {
                onboarded = value;
            }
        }
        
        public string Server
        {
            get
            {
                return server;
            }
            set
            {
                server = value;
            }
        }
        
        public System.DateTime LastHb
        {
            get
            {
                return last_hb;
            }
            set
            {
                last_hb = value;
            }
        }
        
        public string OsVersion
        {
            get
            {
                return os_version;
            }
            set
            {
                os_version = value;
            }
        }
        
        public string LastWifiAlert
        {
            get
            {
                return last_wifi_alert;
            }
            set
            {
                last_wifi_alert = value;
            }
        }
        
        public int WifiAlertCount
        {
            get
            {
                return wifi_alert_count;
            }
            set
            {
                wifi_alert_count = value;
            }
        }
        
        public System.DateTime LastOfflineAlert
        {
            get
            {
                return last_offline_alert;
            }
            set
            {
                last_offline_alert = value;
            }
        }
        
        public int OfflineAlertCount
        {
            get
            {
                return offline_alert_count;
            }
            set
            {
                offline_alert_count = value;
            }
        }
        
        public int TableUpdateSequence
        {
            get
            {
                return table_update_sequence;
            }
            set
            {
                table_update_sequence = value;
            }
        }
        
        public string FeaturePlanId
        {
            get
            {
                return feature_plan_id;
            }
            set
            {
                feature_plan_id = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
        
        public int NetworkId
        {
            get
            {
                return network_id;
            }
            set
            {
                network_id = value;
            }
        }
        
        public int WifiStrength
        {
            get
            {
                return wifi_strength;
            }
            set
            {
                wifi_strength = value;
            }
        }
    }
}
