//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Network
    {
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="wifi_strength")]
        private int wifi_strength;
        
        [DataMember(Name="status")]
        private string status;
        
        [DataMember(Name="armed")]
        private bool armed;
        
        [DataMember(Name="notifications")]
        private int notifications;
        
        [DataMember(Name="warning")]
        private int warning;
        
        [DataMember(Name="enable_temp_alerts")]
        private bool enable_temp_alerts;
        
        [DataMember(Name="error_msg")]
        private string error_msg;
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public int WifiStrength
        {
            get
            {
                return wifi_strength;
            }
            set
            {
                wifi_strength = value;
            }
        }
        
        public string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
        
        public bool Armed
        {
            get
            {
                return armed;
            }
            set
            {
                armed = value;
            }
        }
        
        public int Notifications
        {
            get
            {
                return notifications;
            }
            set
            {
                notifications = value;
            }
        }
        
        public int Warning
        {
            get
            {
                return warning;
            }
            set
            {
                warning = value;
            }
        }
        
        public bool EnableTempAlerts
        {
            get
            {
                return enable_temp_alerts;
            }
            set
            {
                enable_temp_alerts = value;
            }
        }
        
        public string ErrorMsg
        {
            get
            {
                return error_msg;
            }
            set
            {
                error_msg = value;
            }
        }
    }
}
