//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class NetworkDetail
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="created_at")]
        private System.DateTime created_at;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="network_key")]
        private string network_key;
        
        [DataMember(Name="description")]
        private string description;
        
        [DataMember(Name="network_origin")]
        private string network_origin;
        
        [DataMember(Name="locale")]
        private string locale;
        
        [DataMember(Name="time_zone")]
        private string time_zone;
        
        [DataMember(Name="dst")]
        private bool dst;
        
        [DataMember(Name="ping_interval")]
        private int ping_interval;
        
        [DataMember(Name="encryption_key")]
        private string encryption_key;
        
        [DataMember(Name="armed")]
        private bool armed;
        
        [DataMember(Name="autoarm_geo_enable")]
        private bool autoarm_geo_enable;
        
        [DataMember(Name="autoarm_time_enable")]
        private bool autoarm_time_enable;
        
        [DataMember(Name="lv_mode")]
        private string lv_mode;
        
        [DataMember(Name="lfr_channel")]
        private int lfr_channel;
        
        [DataMember(Name="video_destination")]
        private string video_destination;
        
        [DataMember(Name="storage_used")]
        private int storage_used;
        
        [DataMember(Name="storage_total")]
        private int storage_total;
        
        [DataMember(Name="video_count")]
        private int video_count;
        
        [DataMember(Name="video_history_count")]
        private int video_history_count;
        
        [DataMember(Name="arm_string")]
        private string arm_string;
        
        [DataMember(Name="busy")]
        private bool busy;
        
        [DataMember(Name="camera_error")]
        private bool camera_error;
        
        [DataMember(Name="sync_module_error")]
        private bool sync_module_error;
        
        [DataMember(Name="feature_plan_id")]
        private string feature_plan_id;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public System.DateTime CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public string NetworkKey
        {
            get
            {
                return network_key;
            }
            set
            {
                network_key = value;
            }
        }
        
        public string Description
        {
            get
            {
                return description;
            }
            set
            {
                description = value;
            }
        }
        
        public string NetworkOrigin
        {
            get
            {
                return network_origin;
            }
            set
            {
                network_origin = value;
            }
        }
        
        public string Locale
        {
            get
            {
                return locale;
            }
            set
            {
                locale = value;
            }
        }
        
        public string TimeZone
        {
            get
            {
                return time_zone;
            }
            set
            {
                time_zone = value;
            }
        }
        
        public bool Dst
        {
            get
            {
                return dst;
            }
            set
            {
                dst = value;
            }
        }
        
        public int PingInterval
        {
            get
            {
                return ping_interval;
            }
            set
            {
                ping_interval = value;
            }
        }
        
        public string EncryptionKey
        {
            get
            {
                return encryption_key;
            }
            set
            {
                encryption_key = value;
            }
        }
        
        public bool Armed
        {
            get
            {
                return armed;
            }
            set
            {
                armed = value;
            }
        }
        
        public bool AutoarmGeoEnable
        {
            get
            {
                return autoarm_geo_enable;
            }
            set
            {
                autoarm_geo_enable = value;
            }
        }
        
        public bool AutoarmTimeEnable
        {
            get
            {
                return autoarm_time_enable;
            }
            set
            {
                autoarm_time_enable = value;
            }
        }
        
        public string LvMode
        {
            get
            {
                return lv_mode;
            }
            set
            {
                lv_mode = value;
            }
        }
        
        public int LfrChannel
        {
            get
            {
                return lfr_channel;
            }
            set
            {
                lfr_channel = value;
            }
        }
        
        public string VideoDestination
        {
            get
            {
                return video_destination;
            }
            set
            {
                video_destination = value;
            }
        }
        
        public int StorageUsed
        {
            get
            {
                return storage_used;
            }
            set
            {
                storage_used = value;
            }
        }
        
        public int StorageTotal
        {
            get
            {
                return storage_total;
            }
            set
            {
                storage_total = value;
            }
        }
        
        public int VideoCount
        {
            get
            {
                return video_count;
            }
            set
            {
                video_count = value;
            }
        }
        
        public int VideoHistoryCount
        {
            get
            {
                return video_history_count;
            }
            set
            {
                video_history_count = value;
            }
        }
        
        public string ArmString
        {
            get
            {
                return arm_string;
            }
            set
            {
                arm_string = value;
            }
        }
        
        public bool Busy
        {
            get
            {
                return busy;
            }
            set
            {
                busy = value;
            }
        }
        
        public bool CameraError
        {
            get
            {
                return camera_error;
            }
            set
            {
                camera_error = value;
            }
        }
        
        public bool SyncModuleError
        {
            get
            {
                return sync_module_error;
            }
            set
            {
                sync_module_error = value;
            }
        }
        
        public string FeaturePlanId
        {
            get
            {
                return feature_plan_id;
            }
            set
            {
                feature_plan_id = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
    }
}
