//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Programs
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="network_id")]
        private int network_id;
        
        [DataMember(Name="status")]
        private string status;
        
        [DataMember(Name="name")]
        private string name;
        
        [DataMember(Name="schedule")]
        private System.Collections.Generic.List<BlinkdotNet.Entities.Schedule> schedule;
        
        [DataMember(Name="format")]
        private string format;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public int NetworkId
        {
            get
            {
                return network_id;
            }
            set
            {
                network_id = value;
            }
        }
        
        public string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public System.Collections.Generic.List<BlinkdotNet.Entities.Schedule> Schedule
        {
            get
            {
                return schedule;
            }
            set
            {
                schedule = value;
            }
        }
        
        public string Format
        {
            get
            {
                return format;
            }
            set
            {
                format = value;
            }
        }
    }
}
