//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Regions
    {
        
        [DataMember(Name="us")]
        private BlinkdotNet.Entities.Region us;
        
        [DataMember(Name="eu")]
        private BlinkdotNet.Entities.Region eu;
        
        [DataMember(Name="sg")]
        private BlinkdotNet.Entities.Region sg;
        
        public BlinkdotNet.Entities.Region Us
        {
            get
            {
                return us;
            }
            set
            {
                us = value;
            }
        }
        
        public BlinkdotNet.Entities.Region Eu
        {
            get
            {
                return eu;
            }
            set
            {
                eu = value;
            }
        }
        
        public BlinkdotNet.Entities.Region Sg
        {
            get
            {
                return sg;
            }
            set
            {
                sg = value;
            }
        }
    }
}
