//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class Region
    {
        
        [DataMember(Name="dns")]
        private string dns;
        
        [DataMember(Name="friendly_name")]
        private string friendly_name;
        
        [DataMember(Name="registration")]
        private bool registration;
        
        public string Dns
        {
            get
            {
                return dns;
            }
            set
            {
                dns = value;
            }
        }
        
        public string FriendlyName
        {
            get
            {
                return friendly_name;
            }
            set
            {
                friendly_name = value;
            }
        }
        
        public bool Registration
        {
            get
            {
                return registration;
            }
            set
            {
                registration = value;
            }
        }
    }
}
