//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class SensorInformation
    {
        
        [DataMember(Name="lfr")]
        private int lfr;
        
        [DataMember(Name="wifi")]
        private int wifi;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="temp")]
        private int temp;
        
        [DataMember(Name="battery")]
        private int battery;
        
        public int Lfr
        {
            get
            {
                return lfr;
            }
            set
            {
                lfr = value;
            }
        }
        
        public int Wifi
        {
            get
            {
                return wifi;
            }
            set
            {
                wifi = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public int Temp
        {
            get
            {
                return temp;
            }
            set
            {
                temp = value;
            }
        }
        
        public int Battery
        {
            get
            {
                return battery;
            }
            set
            {
                battery = value;
            }
        }
    }
}
