//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace BlinkdotNet.Entities
{
    
    
    [DataContract()]
    public class VideoInformation
    {
        
        [DataMember(Name="id")]
        private int id;
        
        [DataMember(Name="created_at")]
        private System.DateTime created_at;
        
        [DataMember(Name="updated_at")]
        private System.DateTime updated_at;
        
        [DataMember(Name="camera_name")]
        private string camera_name;
        
        [DataMember(Name="description")]
        private string description;
        
        [DataMember(Name="length")]
        private int length;
        
        [DataMember(Name="size")]
        private int size;
        
        [DataMember(Name="upload_time")]
        private int upload_time;
        
        [DataMember(Name="viewed")]
        private System.DateTime viewed;
        
        [DataMember(Name="locked")]
        private bool locked;
        
        [DataMember(Name="ready")]
        private bool ready;
        
        [DataMember(Name="encryption")]
        private string encryption;
        
        [DataMember(Name="encryption_key")]
        private string encryption_key;
        
        [DataMember(Name="storage_location")]
        private string storage_location;
        
        [DataMember(Name="thumbnail")]
        private string thumbnail;
        
        [DataMember(Name="address")]
        private string address;
        
        [DataMember(Name="account_id")]
        private int account_id;
        
        [DataMember(Name="network_id")]
        private int network_id;
        
        [DataMember(Name="camera_id")]
        private int camera_id;
        
        [DataMember(Name="event_id")]
        private string event_id;
        
        [DataMember(Name="partial")]
        private bool @partial;
        
        [DataMember(Name="network_name")]
        private string network_name;
        
        [DataMember(Name="time_zone")]
        private string time_zone;
        
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public System.DateTime CreatedAt
        {
            get
            {
                return created_at;
            }
            set
            {
                created_at = value;
            }
        }
        
        public System.DateTime UpdatedAt
        {
            get
            {
                return updated_at;
            }
            set
            {
                updated_at = value;
            }
        }
        
        public string CameraName
        {
            get
            {
                return camera_name;
            }
            set
            {
                camera_name = value;
            }
        }
        
        public string Description
        {
            get
            {
                return description;
            }
            set
            {
                description = value;
            }
        }
        
        public int Length
        {
            get
            {
                return length;
            }
            set
            {
                length = value;
            }
        }
        
        public int Size
        {
            get
            {
                return size;
            }
            set
            {
                size = value;
            }
        }
        
        public int UploadTime
        {
            get
            {
                return upload_time;
            }
            set
            {
                upload_time = value;
            }
        }
        
        public System.DateTime Viewed
        {
            get
            {
                return viewed;
            }
            set
            {
                viewed = value;
            }
        }
        
        public bool Locked
        {
            get
            {
                return locked;
            }
            set
            {
                locked = value;
            }
        }
        
        public bool Ready
        {
            get
            {
                return ready;
            }
            set
            {
                ready = value;
            }
        }
        
        public string Encryption
        {
            get
            {
                return encryption;
            }
            set
            {
                encryption = value;
            }
        }
        
        public string EncryptionKey
        {
            get
            {
                return encryption_key;
            }
            set
            {
                encryption_key = value;
            }
        }
        
        public string StorageLocation
        {
            get
            {
                return storage_location;
            }
            set
            {
                storage_location = value;
            }
        }
        
        public string Thumbnail
        {
            get
            {
                return thumbnail;
            }
            set
            {
                thumbnail = value;
            }
        }
        
        public string Address
        {
            get
            {
                return address;
            }
            set
            {
                address = value;
            }
        }
        
        public int AccountId
        {
            get
            {
                return account_id;
            }
            set
            {
                account_id = value;
            }
        }
        
        public int NetworkId
        {
            get
            {
                return network_id;
            }
            set
            {
                network_id = value;
            }
        }
        
        public int CameraId
        {
            get
            {
                return camera_id;
            }
            set
            {
                camera_id = value;
            }
        }
        
        public string EventId
        {
            get
            {
                return event_id;
            }
            set
            {
                event_id = value;
            }
        }
        
        public bool Partial
        {
            get
            {
                return @partial;
            }
            set
            {
                @partial = value;
            }
        }
        
        public string NetworkName
        {
            get
            {
                return network_name;
            }
            set
            {
                network_name = value;
            }
        }
        
        public string TimeZone
        {
            get
            {
                return time_zone;
            }
            set
            {
                time_zone = value;
            }
        }
    }
}
