using System;
using System.Text;

namespace BlinkdotNet.Net.Entities
{
    public class Camera
    {
        public int camera_id { get; set; }
        public DateTime created_at { get; set; }
        public DateTime updated_at { get; set; }
        public int wifi_strength { get; set; }
        public int lfr_strength { get; set; }
        public int battery_voltage { get; set; }
        public int temperature { get; set; }
        public string fw_version { get; set; }
        public string mac { get; set; }
        public string ipv { get; set; }
        public string ip_address { get; set; }
        public int error_codes { get; set; }
        public bool battery_alert_status { get; set; }
        public bool temp_alert_status { get; set; }
        public bool ac_power { get; set; }
        public int light_sensor_ch0 { get; set; }
        public int light_sensor_ch1 { get; set; }
        public bool light_sensor_data_valid { get; set; }
        public bool light_sensor_data_new { get; set; }
        public int time_first_video { get; set; }
        public int time_108_boot { get; set; }
        public int time_wlan_connect { get; set; }
        public int time_dhcp_lease { get; set; }
        public int time_dns_resolve { get; set; }
        public int lfr_108_wakeups { get; set; }
        public int total_108_wakeups { get; set; }
        public int lfr_tb_wakeups { get; set; }
        public int total_tb_wakeups { get; set; }
        public int wifi_connect_failure_count { get; set; }
        public int dhcp_failure_count { get; set; }
        public int socket_failure_count { get; set; }
        public int dev_1 { get; set; }
        public int dev_2 { get; set; }
        public int dev_3 { get; set; }
        public int unit_number { get; set; }
        public string serial { get; set; }
        public int lifetime_count { get; set; }
        public int lifetime_duration { get; set; }
        public int pir_rejections { get; set; }
        public int sync_module_id { get; set; }
        public int network_id { get; set; }
        public int account_id { get; set; }
        public int id { get; set; }
        public string deleted_at { get; set; }
        public string camera_key { get; set; }
        public string mac_address { get; set; }
        public string thumbnail { get; set; }
        public string name { get; set; }
        public string liveview_enabled { get; set; }
        public bool siren_enable { get; set; }
        public string siren_volume { get; set; }
        public bool onboarded { get; set; }
        public int motion_sensitivity { get; set; }
        public bool enabled { get; set; }
        public bool alert_tone_enable { get; set; }
        public int alert_tone_volume { get; set; }
        public string alert_repeat { get; set; }
        public int alert_interval { get; set; }
        public int video_length { get; set; }
        public bool temp_alarm_enable { get; set; }
        public int temp_interval { get; set; }
        public int temp_adjust { get; set; }
        public string temp_min { get; set; }
        public string temp_max { get; set; }
        public string temp_hysteresis { get; set; }
        public string illuminator_enable { get; set; }
        public int illuminator_duration { get; set; }
        public int illuminator_intensity { get; set; }
        public bool battery_alarm_enable { get; set; }
        public int battery_voltage_interval { get; set; }
        public int battery_voltage_threshold { get; set; }
        public int battery_voltage_hysteresis { get; set; }
        public string last_battery_alert { get; set; }
        public int battery_alert_count { get; set; }
        public int lfr_sync_interval { get; set; }
        public string video_50_60hz { get; set; }
        public bool invert_image { get; set; }
        public bool flip_image { get; set; }
        public bool record_audio_enable { get; set; }
        public int clip_rate { get; set; }
        public int liveview_rate { get; set; }
        public string max_resolution { get; set; }
        public bool auto_test { get; set; }
        public int wifi_timeout { get; set; }
        public int retry_count { get; set; }
        public string status { get; set; }
        public bool a1 { get; set; }
        public string last_temp_alert { get; set; }
        public int temp_alert_count { get; set; }
        public string last_wifi_alert { get; set; }
        public int wifi_alert_count { get; set; }
        public string last_lfr_alert { get; set; }
        public int lfr_alert_count { get; set; }
        public DateTime? last_offline_alert { get; set; }
        public int offline_alert_count { get; set; }
        public string temp_alert_state { get; set; }
        public string battery_state { get; set; }
        public DateTime battery_check_time { get; set; }
        public int motion_regions { get; set; }
        public string mfg_main_type { get; set; }
        public int mfg_main_range { get; set; }
        public string mfg_mez_type { get; set; }
        public int mfg_mez_range { get; set; }
        public string type { get; set; }
    }
}
